---
title: "POLS 3604: Congress in Theory & Practice"
author: 
  - name: Jason Byers
    email: jason.byers@uconn.edu
date: today
---

Welcome to our course website! Here you can find links to everything you'll need this semester:

-   The course [syllabus](https://byersjs.github.io/POLS-3604-Syllabus/)

-   Submit assignments at our course [HuskyCT page](https://huskyct.uconn.edu) (mortarboard icon in the upper right).

-   I will post lecture notes on the course [GitHub repository](https://github.com/byersjs/POLS-3604) (the octocat icon in the upper right).

# Course Description
This course is an introduction to the political and legislative process of the United States Congress. The course will focus on a semester-long legislative simulation in which students will play the role of United States Senators. Students will organize the legislature, form parties and caucuses, select their own leaders, draft their own bills, debate, and vote on legislation. The first part of the course will consist of traditional lectures to familiarize students with how Congress works; the rest of the semester will be primarily devoted to the legislative simulation.

# Learning Outcomes
Together, we will strive for your individual and collective success in achieving the learning outcomes of this course. At the conclusion of this course, students will be able to:

- Understand the evolution of the legislative process through American history.
- Describe prominent concepts, theories, positions, and problems at stake in the study and practice of legislative politics.
- Demonstrate an appreciation for:

  – The role of Congress in lawmaking and society.
    
  – The goals and constraints shaping legislative behavior.
    
  – The legislative process, its logic, and the potential implications of reforms.
    
  – The value of information and the importance of agenda setting in policymaking.
- Improve communication and listening skills.
- Improve collaborative skills.
- Improve ability to plan and execute a strategy.
- Become an effective representative and legislator.

# Course Materials
To maximize access to this class, we will use textbooks, scientific research papers, and other resources, with a focus on the following:

- Primary Text (TUSC): Adler, E. Scott, Jeffery A. Jenkins, and Charles R. Shipan. 2021. [The United States Congress](https://wwnorton.com/books/9780393428254/about-the-book/description). 2nd Edition. W. W. Norton & Company. This textbook is available for purchase in the bookstore, but students are welcome to purchase the book elsewhere. 